Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  MaxHeaderBytes: 20
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConnection: 10
  MaxOpenConnection: 30
